USE proyecto;
CREATE TABLE IF NOT EXISTS bus (id INT AUTO_INCREMENT NOT NULL, plate_num VARCHAR(7) NOT NULL, model VARCHAR(255) DEFAULT NULL, join_date DATE NOT NULL, km_count INT NOT NULL, last_serv DATE NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS route (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS route_stations (id INT AUTO_INCREMENT NOT NULL, route_id INT NOT NULL, station_id INT NOT NULL, position INT NOT NULL, INDEX IDX_59DB3DC234ECB4E6 (route_id), INDEX IDX_59DB3DC221BDB235 (station_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS station (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, location VARCHAR(500) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS station_route (station_id INT NOT NULL, route_id INT NOT NULL, INDEX IDX_5A425F4F21BDB235 (station_id), INDEX IDX_5A425F4F34ECB4E6 (route_id), PRIMARY KEY(station_id, route_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS ticket (id INT AUTO_INCREMENT NOT NULL, owner_id INT NOT NULL, travel_id INT NOT NULL, INDEX IDX_97A0ADA37E3C61F9 (owner_id), INDEX IDX_97A0ADA3ECAB15B3 (travel_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS travel (id INT AUTO_INCREMENT NOT NULL, date DATE NOT NULL, start_hour TIME NOT NULL, end_hour TIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS `user` (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, mail VARCHAR(255) NOT NULL, citizen_id VARCHAR(9) DEFAULT NULL, UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME (username), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL, INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
ALTER TABLE route_stations ADD CONSTRAINT FK_59DB3DC234ECB4E6 FOREIGN KEY (route_id) REFERENCES route (id);
ALTER TABLE route_stations ADD CONSTRAINT FK_59DB3DC221BDB235 FOREIGN KEY (station_id) REFERENCES station (id);
ALTER TABLE station_route ADD CONSTRAINT FK_5A425F4F21BDB235 FOREIGN KEY (station_id) REFERENCES station (id) ON DELETE CASCADE;
ALTER TABLE station_route ADD CONSTRAINT FK_5A425F4F34ECB4E6 FOREIGN KEY (route_id) REFERENCES route (id) ON DELETE CASCADE;
ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA37E3C61F9 FOREIGN KEY (owner_id) REFERENCES `user` (id);
ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3ECAB15B3 FOREIGN KEY (travel_id) REFERENCES travel (id);

ALTER TABLE user ADD join_date DATE NOT NULL DEFAULT (CURRENT_DATE), ADD phone VARCHAR(9) NOT NULL;
DROP INDEX IDX_75EA56E0FB7336F0 ON messenger_messages;
DROP INDEX IDX_75EA56E0E3BD61CE ON messenger_messages;
DROP INDEX IDX_75EA56E016BA31DB ON messenger_messages;
CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id);

ALTER TABLE route_stations DROP FOREIGN KEY FK_59DB3DC234ECB4E6;
CREATE TABLE routes (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE station_routes (station_id INT NOT NULL, routes_id INT NOT NULL, INDEX IDX_FD37D15521BDB235 (station_id), INDEX IDX_FD37D155AE2C16DC (routes_id), PRIMARY KEY(station_id, routes_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
ALTER TABLE station_routes ADD CONSTRAINT FK_FD37D15521BDB235 FOREIGN KEY (station_id) REFERENCES station (id) ON DELETE CASCADE;
ALTER TABLE station_routes ADD CONSTRAINT FK_FD37D155AE2C16DC FOREIGN KEY (routes_id) REFERENCES routes (id) ON DELETE CASCADE;

DROP TABLE station_route;
DROP TABLE route;
ALTER TABLE bus ADD num_seat INT DEFAULT 1 NOT NULL, CHANGE join_date join_date DATE NOT NULL, CHANGE km_count km_count INT NOT NULL, CHANGE last_serv last_serv DATE NOT NULL;
ALTER TABLE route_stations DROP FOREIGN KEY FK_59DB3DC234ECB4E6;
ALTER TABLE route_stations ADD CONSTRAINT FK_59DB3DC234ECB4E6 FOREIGN KEY (route_id) REFERENCES routes (id);
ALTER TABLE user CHANGE join_date join_date DATE NOT NULL;

ALTER TABLE route_stations ADD CONSTRAINT FK_59DB3DC234ECB4E6 FOREIGN KEY (route_id) REFERENCES routes (id);
ALTER TABLE station ADD address VARCHAR(255) NOT NULL;
ALTER TABLE station ADD phone VARCHAR(9) NOT NULL, ADD city VARCHAR(255) NOT NULL;
ALTER TABLE user CHANGE join_date join_date DATE NOT NULL;
ALTER TABLE bus ADD delist TINYINT(1) NOT NULL;
ALTER TABLE routes ADD delist TINYINT(1) NOT NULL;
ALTER TABLE station ADD delist TINYINT(1) NOT NULL;
ALTER TABLE user CHANGE join_date join_date DATE NOT NULL;
ALTER TABLE route_stations ADD time_to_next TIME NOT NULL;