import React from 'react'
import { useNavigate } from 'react-router-dom'

const Policy = () => {
    const navigate = useNavigate()

    return (
        <div className="app-container">
            <div className="page-container max-w-7xl mx-auto px-4 sm:px-10">
                <div className="page-header">
                    <div className="flex items-center justify-between">
                        <h1>Privacy Policy</h1>
                        <button
                            className="btn btn-secondary"
                            onClick={() => navigate("/home")}
                        >
                            ← Back to main page
                        </button>
                    </div>
                </div>

                <div className="card my-8 p-5">
                    <p className=''>
                        <b>Effective Date: 16/05/2026</b>
                        <br />
                        <b>Last Updated: 16/05/2026</b>
                        <br /><br />

Welcome to Saal (hereinafter referred to as the "Service", "Project", "we", "us", or "our"). We are committed to maintaining the highest standard of privacy.
<br />
This Privacy Policy outlines our strict policies regarding user data. By accessing or using the Service, you acknowledge and agree to the terms outlined below. If you do not agree with these terms, you must discontinue use of the Service immediately.
<br /><br />
<b>1. Data Utilization Policy</b>
<br />
Saal operates on a strict zero-utilization framework regarding your data.
<br />
&nbsp;&nbsp;&nbsp;No Analytics or Tracking: We do not track your digital footprint, monitor your behavior on the Service, or use analytical software to assess your usage patterns.
<br />
&nbsp;&nbsp;&nbsp;No Monetization: Any data generated by your profile or your use of the web application is entirely inert. It is not harvested, sold, traded, or transferred to any third parties, advertisers, or data brokers under any circumstances.
<br />
&nbsp;&nbsp;&nbsp;No Internal Use: We do not use your profile data to train algorithms, personalize content, or improve services. Your interaction with the platform remains strictly your own.
<br /><br />
<b>2. Strict Prohibition of Sensitive Information</b>
<br />
Because this Service is designed as a proof of concept and it's security features fairly basic, Saal does not expect to securely store, process, or protect personal data, therefore, users are strictly prohibited from submitting, uploading, or otherwise transmitting personally identifiable information (PII) or sensitive data.
<br />
When creating a profile or utilizing the Service, you must NOT use or input:
<br />
&nbsp;&nbsp;&nbsp;Real Identities: Do not use your real full name; use a pseudonym or handle.
<br />
&nbsp;&nbsp;&nbsp;Contact Information: Do not input real email addresses, phone numbers, or physical addresses.
<br />
&nbsp;&nbsp;&nbsp;Financial Data: Do not enter credit card numbers, banking details, or any other financial metrics.
<br />
&nbsp;&nbsp;&nbsp;Confidential Information: Do not input passwords used for other services, social security numbers, national identification numbers.
<br />
Note: Any data entered into this platform should be considered non-secure or highly vulnerable. The Service assumes no liability for the exposure of personal or sensitive information that a user voluntarily and improperly uploads in violation of this policy.
<br /><br />
<b>3. Cookies and Local Storage</b>
<br />
The Service may utilize basic local storage (such as strictly necessary session cookies or browser local storage) solely for the mechanical operation of the site (e.g., keeping your session active or remembering a UI preference).
<br />
&nbsp;&nbsp;&nbsp;These mechanisms are completely localized to your device.
<br />
&nbsp;&nbsp;&nbsp;We do not deploy tracking cookies, pixel tags, or third-party surveillance scripts.
<br />
<br />
<b>4. Third-Party Links and Services</b>
<br />
The Service may contain links to external websites that are not operated by us. We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third-party sites or services. We strongly advise you to review the Privacy Policy of every site you visit.
<br /><br />
<b>5. Limitation of Liability</b>
<br />
By utilizing this Service, you acknowledge that Saal is an independent project. Because we strictly mandate that no real, sensitive, or personal data be submitted, we disclaim any and all liability for data breaches, leaks, or the compromise of any personal information that you chose to upload in direct violation of Section 2 of this agreement.
<br /><br />
<b>6. Changes to This Privacy Policy</b>
<br />
We reserve the right to update or modify our Privacy Policy at any time. Any changes will be posted on this page with an updated "Effective Date." Your continued use of the Service after any modifications indicates your acceptance of the updated terms.
<br /><br />
<b>7. Contact Information</b>
<br />
If you have any questions, concerns, or inquiries regarding this Privacy Policy or the operational mechanics of the Service, please contact us at:
<br />
&nbsp;&nbsp;&nbsp;Email: <a href="mailto:marinvilchesmartin@gmail.com">marinvilchesmartin@gmail.com</a>
<br />
&nbsp;&nbsp;&nbsp;Project Repository/Website: <a href="https://github.com/THElib03/proyecto">github.com/THElib03/proyecto</a>
                    </p>
                </div>
            </div>
        </div>
    )
}

export default Policy